{
 "title": "Automation Analytics",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "tower-analytics-stage,tower-analytics-prod"
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{service=~\"automation-analytics-.*\"}",
     "legendFormat": "{{service}}, pod: {{pod}}"
    }
   ]
  },
  { "title": "Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Ingress received payloads per day [code = 202]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ingress_responses{useragent=~\"(Red Hat Ansible Tower.*)|(python-requests.*)|(AWX.*)\", code=\"202\"}[1d]))",
     "legendFormat": "Successful ingress uploads per day"
    }
   ]
  },
  {
   "title": "Ingress received payloads per day [code != 202] by code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ingress_responses{useragent=~\"(Red Hat Ansible Tower.*)|(python-requests.*)|(AWX.*)\", code!=\"202\"}[1d])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Ingress received payloads per minute [code = 202]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ingress_responses{useragent=~\"(Red Hat Ansible Tower.*)|(python-requests.*)|(AWX.*)\", code=\"202\"}[$__interval])*60)",
     "legendFormat": "Successful ingress uploads per minute"
    }
   ]
  },
  {
   "title": "Ingress received payloads per minute [code != 202] by code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ingress_responses{useragent=~\"(Red Hat Ansible Tower.*)|(python-requests.*)|(AWX.*)\", code!=\"202\"}[$__interval])*60) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Ingress received payloads per day [code = 202] by client",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ingress_responses{useragent=~\"(Red Hat Ansible Tower.*)|(python-requests.*)|(AWX.*)\", code=\"202\"}[1d])) by (useragent, code)",
     "legendFormat": "{{useragent}}"
    }
   ]
  },
  {
   "title": "Ingress received payloads per day [code != 202] by client and code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ingress_responses{useragent=~\"(Red Hat Ansible Tower.*)|(python-requests.*)|(AWX.*)\", code!=\"202\"}[1d])) by (useragent, code)",
     "legendFormat": "code: {{code}}, agent: {{useragent}}"
    }
   ]
  },
  { "title": "Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Processor processing rate per day",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ta_processor_message_processed_total{namespace=~\"$namespace\", pod=~\"automation-analytics-processor.*\"}[1d]))",
     "legendFormat": "Processed payloads past day"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (container) (kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace\", container=~\"automation-analytics-processor.*\"})",
     "legendFormat": "CPU limit"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubelet\", image!=\"\", namespace=~\"$namespace\", pod=~\"automation-analytics-processor.*\"}[5m])) by (pod)",
     "legendFormat": "CPU usage: {{ pod }}"
    },
    {
     "expr": "max by (container) (kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\", container=~\"automation-analytics-processor.*\"})",
     "legendFormat": "CPU request"
    },
    {
     "expr": "sum(\n    rate(container_cpu_cfs_throttled_seconds_total{job=\"kubelet\", image!=\"\", pod=~\"automation-analytics-processor.*\", namespace=~\"$namespace\"}[5m])) \nby (pod)",
     "legendFormat": "CPU throttled: {{ pod }}"
    }
   ]
  },
  {
   "title": "Processor processed bytes per day",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"automation-analytics-processor.*\"}[1d]))",
     "legendFormat": "Transmit total"
    },
    {
     "expr": "sum(increase(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"automation-analytics-processor.*\"}[1d]))",
     "legendFormat": "Receive total"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max by (container) (kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace\", container=~\"automation-analytics-processor.*\"})",
     "legendFormat": "Memory limit: {{ container }}"
    },
    {
     "expr": "sum((container_memory_working_set_bytes{namespace=\"$namespace\", container=\"automation-analytics-processor\", pod=~\"automation-analytics-processor.*\"})) by (pod)",
     "legendFormat": "Usage bytes: {{ pod }}"
    }
   ]
  },
  {
   "title": "Processor processing rate per minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ta_processor_message_processed_total{namespace=~\"$namespace\", pod=~\"automation-analytics-processor.*\"}[$__interval])*60) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"automation-analytics-processor.*\"}[5m])) by (pod)",
     "legendFormat": "Transmit bytes: {{ pod }}"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"automation-analytics-processor.*\"}[5m])) by (pod)",
     "legendFormat": "Receive bytes: {{ pod }}"
    }
   ]
  },
  {
   "title": "Processor exception per minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ta_processor_exception_total{namespace=~\"$namespace\", pod=~\"automation-analytics-processor.*\"}[5m])*60",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Processing time",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "sum(increase(ta_processor_processing_time_v2_bucket{pod=~\"automation-analytics-processor.*\"}[1h])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Processor Kafka lag",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_group_lag {topic=\"platform.upload.tower\", group=\"processor\"}) by (partition)",
     "legendFormat": "Partition: {{ partition}}"
    }
   ]
  },
  {
   "title": "Processing time total",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 75 },
   "targets": [
    {
     "expr": "sum(ta_processor_processing_time_v2_bucket{pod=~\"automation-analytics-processor.*\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Processor detail timings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processing time of events",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
     "targets": [
      {
       "expr": "sum(increase(ta_processor_handle_events_table_bucket{pod=~\"automation-analytics-processor.*\"}[1h])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time of jobs",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
     "targets": [
      {
       "expr": "sum(increase(ta_processor_handle_unified_jobs_bucket{pod=~\"automation-analytics-processor.*\"}[1h])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Rollup processor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rollup processor processing rate per day",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(ta_rollup_processor_message_processed_total{namespace=~\"$namespace\", pod=~\"automation-analytics-processor.*\"}[1d]))",
       "legendFormat": "Processed rollups past day"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max by (container) (kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace\", container=~\"automation-analytics-rollup-processor.*\"})",
       "legendFormat": "CPU limit"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubelet\", image!=\"\", namespace=~\"$namespace\", pod=~\"automation-analytics-rollup-processor.*\"}[5m])) by (pod)",
       "legendFormat": "CPU usage: {{ pod }}"
      },
      {
       "expr": "max by (container) (kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\", container=~\"automation-analytics-rollup-processor.*\"})",
       "legendFormat": "CPU request"
      },
      {
       "expr": "sum(\n    rate(container_cpu_cfs_throttled_seconds_total{job=\"kubelet\", image!=\"\", pod=~\"automation-analytics-rollup-processor.*\", namespace=~\"$namespace\"}[5m])) \nby (pod)",
       "legendFormat": "CPU throttled: {{ pod }}"
      }
     ]
    },
    {
     "title": "Rollup processor processing rate per minute",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(ta_rollup_processor_message_processed_total{namespace=~\"$namespace\", pod=~\"automation-analytics-rollup-processor.*\"}[$__interval])*60) by (pod)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 67 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max by (container) (kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace\", container=~\"automation-analytics-rollup-processor.*\"})",
       "legendFormat": "Memory limit: {{ container }}"
      },
      {
       "expr": "sum((container_memory_working_set_bytes{namespace=\"$namespace\", container=\"automation-analytics-processor\", pod=~\"automation-analytics-rollup-processor.*\"})) by (pod)",
       "legendFormat": "Usage bytes: {{ pod }}"
      }
     ]
    },
    {
     "title": "Rollup processor exception per minute",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 76 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(ta_rollup_processor_exception_total{namespace=~\"$namespace\", pod=~\"automation-analytics-rollup-processor.*\"}[5m])*60",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Network usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 76 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"automation-analytics-rollup-processor.*\"}[5m])) by (pod)",
       "legendFormat": "Transmit bytes: {{ pod }}"
      },
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"automation-analytics-rollup-processor.*\"}[5m])) by (pod)",
       "legendFormat": "Receive bytes: {{ pod }}"
      }
     ]
    },
    {
     "title": "Processing time",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 85 },
     "targets": [
      {
       "expr": "sum(increase(ta_rollup_processor_whole_rollup_job_processing_time_bucket{pod=~\"automation-analytics-rollup-processor.*\"}[1h])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time of rollups and running rules",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 85 },
     "targets": [
      {
       "expr": "sum(ta_rollup_processor_whole_rollup_job_processing_time_bucket{pod=~\"automation-analytics-rollup-processor.*\"}) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time of rollup batch (max 2 months)",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 94 },
     "targets": [
      {
       "expr": "sum(ta_rollup_processor_rollup_processing_time_bucket{pod=~\"automation-analytics-rollup-processor.*\"}) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time of running rules",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 94 },
     "targets": [
      {
       "expr": "sum(ta_rollup_processor_run_rules_processing_time_bucket{pod=~\"automation-analytics-rollup-processor.*\"}) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Requests per minute, by status code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ta_api_responses_total{namespace=\"$namespace\", path_template!=\"/metrics\"}[5m])*60) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 87 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (container) (kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace\", container=~\"automation-analytics-api-fastapi.*\"})",
     "legendFormat": "CPU limit"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubelet\", image!=\"\", namespace=~\"$namespace\", pod=~\"automation-analytics-api-fastapi.*\"}[5m])) by (pod)",
     "legendFormat": "CPU usage: {{ pod }}"
    },
    {
     "expr": "max by (container) (kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\", container=~\"automation-analytics-api-fastapi.*\"})",
     "legendFormat": "CPU request"
    },
    {
     "expr": "sum(\n    rate(container_cpu_cfs_throttled_seconds_total{job=\"kubelet\", image!=\"\", pod=~\"automation-analytics-api-fastapi.*\", namespace=~\"$namespace\"}[5m])) \nby (pod)",
     "legendFormat": "CPU throttled: {{ pod }}"
    }
   ]
  },
  {
   "title": "Requests per minute by view ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (path_template) (rate(ta_api_requests_total{namespace=\"$namespace\", path_template!=\"/metrics\"}[30m])*60)",
     "legendFormat": "{{path_template}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max by (container) (kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace\", container=~\"automation-analytics-api-fastapi.*\"})",
     "legendFormat": "Memory limit: {{ container }}"
    },
    {
     "expr": "sum((container_memory_usage_bytes{namespace=\"$namespace\", container=\"automation-analytics-api-fastapi\", pod=~\"automation-analytics-api-fastapi.*\"})) by (pod)",
     "legendFormat": "Usage bytes: {{ pod }}"
    }
   ]
  },
  {
   "title": "Request Errors per minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status_code, path_template) (increase(ta_api_responses_total{namespace=\"$namespace\",status_code=~\"5..\"}[1h]))",
     "legendFormat": "{{status_code}} {{path_template}}"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 105 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"automation-analytics-api-fastapi.*\"}[5m])) by (pod)",
     "legendFormat": "Transmit bytes: {{ pod }}"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"automation-analytics-api-fastapi.*\"}[5m])) by (pod)",
     "legendFormat": "Receive bytes: {{ pod }}"
    }
   ]
  },
  {
   "title": "Request Latency Rate by View",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(ta_api_requests_processing_time_seconds_sum[15m]) / rate(ta_api_requests_processing_time_seconds_count[15m])) by (path_template)",
     "legendFormat": "{{path_template}}"
    }
   ]
  },
  {
   "title": "RDS Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 121 },
   "collapsed": true,
   "panels": [
    {
     "title": "RDS database connections average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_rds_database_connections_average{dbinstance_identifier=\"$namespace\"}",
       "legendFormat": "Guest"
      }
     ]
    },
    {
     "title": "RDS CPU Utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_rds_cpuutilization_average{dbinstance_identifier=\"$namespace\"}",
       "legendFormat": "Guest"
      }
     ]
    },
    {
     "title": "RDS freeable memory average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "aws_rds_freeable_memory_average{dbinstance_identifier=\"$namespace\"}",
       "legendFormat": "Guest"
      }
     ]
    },
    {
     "title": "RDS read IOPs average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_rds_read_iops_average{dbinstance_identifier=\"$namespace\"}",
       "legendFormat": "Guest"
      }
     ]
    },
    {
     "title": "RDS free storage space",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "aws_rds_free_storage_space_average{dbinstance_identifier=\"$namespace\"}",
       "legendFormat": "Guest"
      }
     ]
    },
    {
     "title": "RDS write IOPs average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_rds_write_iops_average{dbinstance_identifier=\"$namespace\"}",
       "legendFormat": "Guest"
      }
     ]
    },
    {
     "title": "RDS transaction logs disk usage average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "aws_rds_transaction_logs_disk_usage_average{dbinstance_identifier=\"$namespace\"}",
       "legendFormat": "Guest"
      }
     ]
    }
   ]
  }
 ]
}