name: Validate PR

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - uses: dschep/install-pipenv-action@v1
    - run: pipenv sync
    - name: run validate_dashboards
      run: pipenv run python validate_dashboards.py
